# Generated by Django 5.0.7 on 2025-09-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_requestcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestcount",
            name="device_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
