# Generated by Django 5.0.7 on 2025-09-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_requestcount_device_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="requestcount",
            unique_together={("user", "device_id", "ip_address")},
        ),
        migrations.AlterField(
            model_name="requestcount",
            name="device_id",
            field=models.CharField(db_index=True, default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="requestcount",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="requestcount",
            name="window_start",
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name="requestcount",
            name="last_request",
        ),
    ]
