# Generated by Django 5.0.7 on 2025-09-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_requestcount_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="requestcount",
            unique_together={("user", "device_id")},
        ),
    ]
